### PR TITLE
TASK: Storybook integration

### PR DESCRIPTION
**Pull request by dimaip**
[Storybook](https://github.com/kadirahq/react-storybook) allows running each UI component in isolation from the rest of UI. It even allows developing UI components without even setting up Neos installation itself!

We can also integrate http://storybooks.io/ when it's launched, so we'd be able to have an online reference and reviewing of UI code, without needing to test the pull request locally.

- [x] Add storeys for all components
- [ ] Documentat the Storybook workflow

### CODE REVIEW

**Comment by dimaip** [comment]
There are some essential documentation features missing for Storybook, but it seems these guys plan to improve on that: https://github.com/kadirahq/react-storybook/issues/166#issuecomment-220327183

**Comment by dimaip** [comment]
I have created storybooks for all of our components.
There are numerous problems with individual components that storybook helped me to spot, but the should be fixed in an independent branch.
I will document the storybook workflow and then I think we can merge this branch.

**Comment by Inkdpixels** [comment]
Looks pretty solid by reading! :) :+1:

**Comment by dimaip** [comment]
@Inkdpixels do you know perhaps why the test is failing? I couldn't have touched anything related to it...

**Comment by Inkdpixels** [comment]
I will take a look at it this evening :)

**Comment by Inkdpixels** [comment]
Hey @dimaip - I checked out your PR locally and I can indeed reproduce this error we are getting on CI. Until tomorrow evening I don't have much time to look into it, but I've found a storybook related issue of some guy which has the same error message, I think that's a good path we can follow. 

I you don't mind waiting, I will try to fix it tomorrow evening :)

https://github.com/kadirahq/react-storybook/issues/174

**Comment by Inkdpixels** [comment]
Hey @dimaip - I've found the location of the error. Basically the problem lies in the `karma.entry.js` file, which will in fact require all `.js` files, since this is important for coverage statistics. The workaround is to adopt the regular expression to something like `/(?!.*story.js$)^.*js$/` which will import all `.js` files but ignores all files which end with `.story.js`. 

I've tested this locally, and it works.Could you either commit this, or give me access to your fork? Thanks buddy :)

**Comment by dimaip** [comment]
@Inkdpixels thanks a lot for helping me out on this! Granted you access. I myself will be able to fix it on Monday, as well as document it.

**Comment by Inkdpixels** [comment]
yay, done :100:

**Comment by Inkdpixels** [comment]
Hey @dimaip - I will merge this if you dont mind, since the only task left seems to be documentation and I also need to work on the previuosly changed `karma.entry` file. :)

**Pull request merged**
